### ISSUE TITLE
Test this code (Less Artifacts same) :D

### ISSUE THREAD

**Issue by iamzuika** [bjaan/smoothvideo#1]
Video Ex: https://drive.google.com/drive/folders/1OMQOkjCJyfBrhpcaR2j4lYXNIq25lEIB?usp=sharing

My code
Smooth : {rate:{num:60,den:1,abs:true},mask:{area:0,cover:80},algo:23,cubic:0,scene:{mode:0,blend:false,limits:{scene:6000,blocks:1}}}
Vectors : {block:{w:32,h:32,overlap:0},main:{search:{distance:-3,type:3,satd:false,sort:true,coarse:{distance:-5,type:2,satd:true,trymany:true,width:481,bad:{range:0}}},levels:4,penalty:{lambda:11.5, plevel:1.6,pnew:44,pglobal:104,pzero:240,pnbour:65,prev:-1}},refine:[{search:{distance:4}}]}
Super : {scale:{up:0,down:0},pel:1,gpu:1,rc:true}

Sry i'm bad english.

**Comment by bjaan** [comment]
It's fantastic to see that the video using your code is noticeably smoother! I can't wait to put it to the test against a video file that previously had some pesky artifacts. Specifically, I'm curious to see how it performs in those challenging scenes, like when an object moves in and out over a sliding static background in animation or during those tricky camera pans while the character is busting a move! 🚀🎥💃🕺

**Comment by iamzuika** [comment]
I'm test base on 2D, But not test on real life.

Sry i'm bad english.

**Comment by bjaan** [comment]
I'm exclusively testing your code on 2D animation at the moment. It appears that your code doesn't implement motion blurring between frames, which mine does. Consequently, in your results, still frames remain static, and background movement persists frame by frame during panning shots. Interestingly, I haven't come across any artifact problems, distortions, or broken shapes in my 4K tests thus far.

Would you mind highlighting a specific frame with an issue where you applied my code in your example? I've been using the "E" button in VLC media player to examine the frames individually.

Summary:

**Zulka code:**
- no motion blur
- smooth pan shots

_super_params="{scale:{up:0,down:0},pel:1,gpu:1,rc:true}"
analyse_params="{block:{w:32,h:32,overlap:0},main:{search:{distance:-3,type:3,satd:false,sort:true,coarse:{distance:-5,type:2,satd:true,trymany:true,width:481,bad:{range:0}}},levels:4,penalty:{lambda:11.5, plevel:1.6,pnew:44,pglobal:104,pzero:240,pnbour:65,prev:-1}},refine:[{search:{distance:4}}]}"
smoothfps_params = "{rate:{num:60,den:1,abs:true},mask:{area:0,cover:80},algo:23,cubic:0,scene:{mode:0,blend:false,limits:{scene:6000,blocks:1}}}"_

**Bjaan code of 29 August:**
- motion blur
- smooth pan shots

_super_params="{pel:1,gpu:1,full:false}"
analyse_params="{block:{w:32,h:32,overlap:0},main:{
search:{distance:-0 ,type:4,satd:false,sort:true,
coarse:{distance:-21,type:2,satd:false,trymany:true,
width:481,bad:{range:0}}},levels:3,penalty:{lambda:3.3,
plevel:1.25,pnew:44,pglobal:104,pzero:240,pnbour:74,prev:-1}}}"
smoothfps_params = "{rate:{num:60, abs:true}, algo:13,mask:{area:200},scene:{} }"_

With motion blurring I mean intra-frame blurring between two different animation frames in the original video, like so:
![vlcsnap-2023-09-02-02h20m58s677](https://github.com/bjaan/smoothvideo/assets/42038171/f46c3ca3-ae2d-40f5-9e9b-7c91b33badb5)

**Comment by iamzuika** [comment]
I have question, You're think have motion blur bester?, because i don't know about this.

**Comment by bjaan** [comment]
I think having a motion blur - it might already part of an original video - depends on the type of footage, and the "feel" you or the creator wants to give the video.  I have asked ChatGPT 3.5 and it says it not really recommended for 2D animation, and it is also not clear from what I see on Wikipedia and other articles I found on Google.

As we can now somehow control it using your code or mine could give interesting results 😉 The code here could be enhanced that would allow one to select "presets"...

This is what ChatGPT 3.5 said:
"
Motion blur can be a subjective matter, and its effectiveness depends on the content and personal preferences.

Motion blur is essentially a visual effect that occurs when an object in motion appears blurred or smeared in a sequence of images or frames. It's commonly used in various types of media to simulate the way our eyes perceive fast-moving objects in the real world.

Whether motion blur is better or not depends on several factors:

1. **Type of Content:** Motion blur is often more noticeable and appreciated in certain types of content. For example, it's commonly used in 3D animation and live-action scenes to create a sense of realism and smoothness in motion. In contrast, 2D animation might not always require motion blur, as it often has a distinct, flat visual style.

2. **Intended Effect:** The decision to use motion blur also depends on the desired effect. Some creators prefer a crisp, clean look without motion blur to maintain the clarity of each frame. Others may choose to apply motion blur for a more cinematic or dynamic feel.

3. **Personal Preference:** Ultimately, it comes down to personal preference. Some viewers and creators prefer the added realism and smoothness that motion blur can provide, while others may prefer a sharper, more stylized look.

So, whether motion blur is "better" or not varies from case to case. It's a tool that can enhance certain types of content and storytelling, but it's not always necessary or appropriate for every situation. The decision to use it should be based on the specific goals and aesthetics of your project.
"
